baseURL = 'https://rifeli.dev/'
copyright = "2015 - {year}"
languageCode = 'en-US'
defaultContentLanguage = 'en'
theme = 'lowkey'
title = 'rifeli.dev'
enableRobotsTXT = true
summaryLength = 15

[params.social]
  github = "https://github.com/leonardorifeli"
  linkedin = "https://www.linkedin.com/in/leonardorifeli"
  website = "https://rifeli.dev"

[pagination]
  pagerSize = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 2
