[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 2

[[main]]
    identifier = "uses"
    name = "uses"
    url = "/uses"
    weight = 3

[[main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 4

# Social Media Configuration

[[social]]
    identifier = "github"
    name = "Github"
    url = "http://github.com/leonardorifeli"
    weight = 1

[[social]]
    identifier = "linkedin"
    name = "Linkedin"
    url = "https://www.linkedin.com/in/leonardorifeli"
    weight = 2

[[social]]
    identifier = "work"
    name = "Startup"
    url = "https://harmo.me"
    weight = 3