# Homepage Config
isSinglePage = false

# Meta Config
description = "Leonardo creates, writes and operates software. 🚀 CTO at Harmo | Data Engineer | Software Architect."

# Header Configuration
avatar = "img/6767689.jpeg"

# disqus is a comment system. see https://disqus.com
disqusShortname = ""

[emoji]
enableEmoji = false

# giscus is a comment system based on GitHub Discussions. see https://giscus.app
[giscus]       
    enable = true
    repo = "leonardorifeli/personal_blog"
    repoId = "R_kgDOK5D89g"
    category = "blog"
    categoryId = "DIC_kwDOK5D89s4Cbsd_"
    mapping = "pathname"  # comment value is the default value
    strict = 0
    reactionsEnabled = 0
    emitMetadata = 1
    inputPosition = "top"
    lang = "en"
    lazyLoading = false