baseURL = "https://rifeli.dev/"
languageCode = "en-us"
title = "Leonardo Rifeli"
theme = "archie"
# googleAnalytics = "UA-3063031-15"
googleAnalytics = "G-MHKZRCJN0C"
disqusShortname = "leonardorifeli"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=4 # articles per page

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true

[markup.goldmark.renderer]
unsafe= true

[minify]
minifyOutput = true

[permalinks]
fixed = ":title/"
blog  = ":slug"

[params]
author = "Thiago Avelino"
mode="toggle" # color-mode → light,dark,toggle or auto
useCDN=true # don't use CDNs for fonts and icons, instead serve them locally.
subtitle = "I'm a Software Craftsman! Remember that there is no code faster than no code. Gopher since 2017"
mathjax = false # enable MathJax support
katex = false # enable KaTeX support
customcss = ["/css/custom.css"]

# Social
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/leonardorifeli"
[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/rifelidev"
[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://www.instagram.com/rifeli.dev/"

# Main menu Items
[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "all posts"
url = "/blog"
weight = 2

[[menu.main]]
name = "about"
url = "/about"
weight = 3
